# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sender.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# for GUI
from PyQt5 import QtCore, QtGui, QtWidgets
# for sending Email
import smtplib
from email.message import EmailMessage

# NOTE: IF IT SHOWS NOT RESPONDING, THEN PLEASE WAIT FOR SOME TIME!!!

class Ui_HelpWindow(object):
    def setupUi(self, HelpWindow):
            
        # Help Window
        HelpWindow.setObjectName("HelpWindow")
        HelpWindow.resize(418, 341)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HelpWindow.sizePolicy().hasHeightForWidth())
        HelpWindow.setSizePolicy(sizePolicy)
        HelpWindow.setMaximumSize(QtCore.QSize(486, 393))
        HelpWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.centralwidget = QtWidgets.QWidget(HelpWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # label 0
        self.label0 = QtWidgets.QLabel(self.centralwidget)
        self.label0.setGeometry(QtCore.QRect(0, 0, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label0.setFont(font)
        self.label0.setAlignment(QtCore.Qt.AlignCenter)
        self.label0.setObjectName("label0")
        
        # label 1
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(0, 20, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        
        # Label 2
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(0, 50, 421, 16))
        self.label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label2.setObjectName("label2")
        
        # label 3
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(0, 70, 421, 16))
        self.label3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label3.setObjectName("label3")
        
        # label 4
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(0, 80, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        
        # label 5
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(0, 110, 421, 16))
        self.label5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label5.setObjectName("label5")
        
        # label 6
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(0, 130, 421, 16))
        self.label6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label6.setObjectName("label6")
        
        # label 7
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        self.label7.setGeometry(QtCore.QRect(0, 150, 421, 16))
        self.label7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label7.setObjectName("label7")
        
        # label 8
        self.label8 = QtWidgets.QLabel(self.centralwidget)
        self.label8.setGeometry(QtCore.QRect(0, 160, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setAlignment(QtCore.Qt.AlignCenter)
        self.label8.setObjectName("label8")
        
        # label 9
        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setGeometry(QtCore.QRect(0, 190, 421, 16))
        self.label9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label9.setObjectName("label9")
        
        # label 10
        self.label10 = QtWidgets.QLabel(self.centralwidget)
        self.label10.setGeometry(QtCore.QRect(0, 210, 421, 16))
        self.label10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label10.setObjectName("label10")
        
        # label 11
        self.label11 = QtWidgets.QLabel(self.centralwidget)
        self.label11.setGeometry(QtCore.QRect(0, 230, 421, 16))
        self.label11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label11.setObjectName("label11")
        
        # label 12
        self.label12 = QtWidgets.QLabel(self.centralwidget)
        self.label12.setGeometry(QtCore.QRect(0, 240, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label12.setFont(font)
        self.label12.setAlignment(QtCore.Qt.AlignCenter)
        self.label12.setObjectName("label12")
        
        # label 13
        self.label13 = QtWidgets.QLabel(self.centralwidget)
        self.label13.setGeometry(QtCore.QRect(0, 270, 421, 31))
        self.label13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label13.setWordWrap(True)
        self.label13.setObjectName("label13")
        HelpWindow.setCentralWidget(self.centralwidget)
        
        # Close Button
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(180, 310, 75, 23))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClose.setStyleSheet("color:black;\n"
"background-color:white;")
        self.btnClose.setObjectName("btnClose")

        # Help Restranslate Ui
        self.retranslateUi(HelpWindow)
        QtCore.QMetaObject.connectSlotsByName(HelpWindow)

    def retranslateUi(self, HelpWindow):
        _translate = QtCore.QCoreApplication.translate
        HelpWindow.setWindowTitle(_translate("HelpWindow", "Help"))
        self.label2.setText(_translate("HelpWindow", "1. Enter you Email in the Email box. "))
        self.btnClose.setText(_translate("HelpWindow", "Close"))
        self.label0.setText(_translate("HelpWindow", "Help"))
        self.label3.setText(_translate("HelpWindow", "2. Enter you Password in Password box."))
        self.label5.setText(_translate("HelpWindow", "3. Enter Email address in To box to whom you wanna send Email."))
        self.label6.setText(_translate("HelpWindow", "4. Enter Subject of the Email in Subject Box."))
        self.label1.setText(_translate("HelpWindow", "From"))
        self.label4.setText(_translate("HelpWindow", "To"))
        self.label7.setText(_translate("HelpWindow", "5. Enter Message of the Email in Message box."))
        self.label8.setText(_translate("HelpWindow", "Still not sending Email???"))
        self.label9.setText(_translate("HelpWindow", "1. Login to your Google Account in Browser."))
        self.label10.setText(_translate("HelpWindow", "2. Go to Security Tab and turn less secure apps access On."))
        self.label11.setText(_translate("HelpWindow", "3. Try sending again!!!"))
        self.label12.setText(_translate("HelpWindow", "OR"))
        self.label13.setText(_translate("HelpWindow", "If you are using two factor authentication On, kindly Turn it off and perform the above 3 steps of Turning less secure apps access On."))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
            
        # Main Window
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(640, 449)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(640, 449))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # App Name Label
        self.AppName = QtWidgets.QLabel(self.centralwidget)
        self.AppName.setGeometry(QtCore.QRect(210, 20, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Hv BT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.AppName.setFont(font)
        self.AppName.setObjectName("AppName")
        
        # From Label
        self.FromLabel = QtWidgets.QLabel(self.centralwidget)
        self.FromLabel.setGeometry(QtCore.QRect(290, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.FromLabel.setFont(font)
        self.FromLabel.setObjectName("FromLabel")
        
        # Email Label
        self.labelEmail = QtWidgets.QLabel(self.centralwidget)
        self.labelEmail.setGeometry(QtCore.QRect(60, 100, 31, 21))
        self.labelEmail.setObjectName("labelEmail")
        
        # Email Line Edit
        self.Email = QtWidgets.QLineEdit(self.centralwidget)
        self.Email.setGeometry(QtCore.QRect(110, 100, 191, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Email.setFont(font)
        self.Email.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Email.setToolTip("")
        self.Email.setWhatsThis("")
        self.Email.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Email.setAutoFillBackground(False)
        self.Email.setStyleSheet("color:black;\n"
"background-color:white;")
        self.Email.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.Email.setText("")
        self.Email.setObjectName("Email")
        
        # Password Label
        self.labelPassword = QtWidgets.QLabel(self.centralwidget)
        self.labelPassword.setGeometry(QtCore.QRect(310, 100, 51, 21))
        self.labelPassword.setObjectName("labelPassword")
        
        # Password Line Edit
        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(370, 100, 191, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Password.setFont(font)
        self.Password.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password.setAutoFillBackground(False)
        self.Password.setStyleSheet("color:black;\n"
"background-color:white;")
        self.Password.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        
        # To Label
        self.ToLabel = QtWidgets.QLabel(self.centralwidget)
        self.ToLabel.setGeometry(QtCore.QRect(300, 130, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ToLabel.setFont(font)
        self.ToLabel.setObjectName("ToLabel")
        
        # Email To Label
        self.labelToList = QtWidgets.QLabel(self.centralwidget)
        self.labelToList.setGeometry(QtCore.QRect(60, 160, 16, 21))
        self.labelToList.setObjectName("labelToList")
        
        # Email To Line Edit
        self.EmailTo = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailTo.setGeometry(QtCore.QRect(110, 160, 451, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.EmailTo.setFont(font)
        self.EmailTo.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.EmailTo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EmailTo.setAutoFillBackground(False)
        self.EmailTo.setStyleSheet("color:black;\n"
"background-color:white;")
        self.EmailTo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.EmailTo.setObjectName("EmailTo")
        
        # Email Subject Label
        self.labelEmailSubject = QtWidgets.QLabel(self.centralwidget)
        self.labelEmailSubject.setGeometry(QtCore.QRect(60, 190, 41, 21))
        self.labelEmailSubject.setObjectName("labelEmailSubject")
        
        # Email Subject Line Edit
        self.EmailSubject = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailSubject.setGeometry(QtCore.QRect(110, 190, 451, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.EmailSubject.setFont(font)
        self.EmailSubject.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.EmailSubject.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EmailSubject.setAutoFillBackground(False)
        self.EmailSubject.setStyleSheet("color:black;\n"
"background-color:white;")
        self.EmailSubject.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.EmailSubject.setObjectName("EmailSubject")
        
        # Email Message Label
        self.labelEmailMessage = QtWidgets.QLabel(self.centralwidget)
        self.labelEmailMessage.setGeometry(QtCore.QRect(60, 220, 47, 13))
        self.labelEmailMessage.setObjectName("labelEmailMessage")
        
        # Email Message Text Edit
        self.EmailMessage = QtWidgets.QTextEdit(self.centralwidget)
        self.EmailMessage.setGeometry(QtCore.QRect(110, 220, 451, 161))
        self.EmailMessage.setStatusTip("")
        self.EmailMessage.setStyleSheet("color:black;\n"
"background-color:white;")
        self.EmailMessage.setObjectName("EmailMessage")
        
        # Cancel Button
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(390, 400, 75, 23))
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCancel.setAutoFillBackground(False)
        self.btnCancel.setStyleSheet("color:black;\n"
"background-color:white;")
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setFlat(False)
        self.btnCancel.setObjectName("btnCancel")
        
        # on click event
        self.btnCancel.clicked.connect(self.Cancel)
        
        # Send Button
        self.btnSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(480, 400, 75, 23))
        self.btnSend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSend.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnSend.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnSend.setAutoFillBackground(False)
        self.btnSend.setStyleSheet("color:black;\n"
"background-color:white;")
        self.btnSend.setAutoDefault(False)
        self.btnSend.setFlat(False)
        self.btnSend.setObjectName("btnSend")
        
        # on click event
        self.btnSend.clicked.connect(self.Send)
        
        # Help Button
        self.btnHelp = QtWidgets.QPushButton(self.centralwidget)
        self.btnHelp.setGeometry(QtCore.QRect(580, 20, 41, 23))
        self.btnHelp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHelp.setStatusTip("")
        self.btnHelp.setStyleSheet("color:black;\n"
"background-color:white;")
        self.btnHelp.setObjectName("btnHelp")
        
        # Success/Error Label
        self.success = QtWidgets.QLabel(self.centralwidget)
        self.success.setGeometry(QtCore.QRect(200, 400, 200, 21))
        self.success.setObjectName("labelsuccess")
        
        # On click event
        self.btnHelp.clicked.connect(self.Help)
        
        # status bar
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # retranslate Ui
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # set tab order
        MainWindow.setTabOrder(self.Email, self.Password)
        MainWindow.setTabOrder(self.Password, self.EmailTo)
        MainWindow.setTabOrder(self.EmailTo, self.EmailSubject)
        MainWindow.setTabOrder(self.EmailSubject, self.EmailMessage)
        MainWindow.setTabOrder(self.EmailMessage, self.btnSend)
        MainWindow.setTabOrder(self.btnSend, self.btnCancel)
    
    # clear the line edits and text areas
    def Clear(self, Value):
        """
        This functions a value input on basis of which it
        clears the line edits and text area.
        
        Clear(True) -> Email has sent successfully Then set
					   EmailTo, EmailSubject, EmailMessage empty.
        Clear(False) -> Email has Authentication errors then set
						Email and Password to empty.
        """
        # if user cancelled to set Email
        if Value == False:
            self.Email.setText("")
            self.Password.setText("")
            self.EmailTo.setText("")
            self.EmailSubject.setText("")
            self.EmailMessage.setText("")
        else:
            # Email has sent Successfully
            self.EmailTo.setText("")
            self.EmailSubject.setText("")
            self.EmailMessage.setText("")
    
    # send Email with given data
    def SendEmail(self, From, Password, To, Subject, Message):
        """
        This function sends Mail through port!
        """
        try:
            # set smtp server with port 587
            server = smtplib.SMTP("smtp.gmail.com", 587)
            # encrypt the server communication using TLS
            server.starttls()
            # login in your credentials
            server.login(From, Password)
            
            # setting up the email
            Email = EmailMessage()
            Email["From"] = From
            Email["To"] = To
            Email["Subject"] = Subject
            Email.set_content(Message)
            
            # sending message ...
            server.send_message(Email)
            # if no error occurs then set Email sent Successfully!
            self.success.setText("Email Sent Successfully!!!")
            # Clear the Mail area 
            self.Clear(False)
            
        # if any authentication error occurs
        except smtplib.SMTPAuthenticationError:
            self.success.setText("Provided Emails/Password is Wrong!!!")
        # if anything is empty, concatenation error occurs
        except TypeError:
            self.success.setText("Incomplete Data!")
        # if anyother error occurs, stop app from crashing
        except:
            pass

	# this will get data required to send message
    def Send(self):
        """
        This function collects data from the GUI required to
        send EMail.
        """
        # collecting from Gui
        From = self.Email.text()
        Password = self.Password.text()
        To = self.EmailTo.text()
        Subject = self.EmailSubject.text()
        Message = self.EmailMessage.toPlainText()
        
        #calling the send mail function to send Email
        self.SendEmail(From, Password, To, Subject, Message)
        
    # this function
    def Cancel(self):
        # if user press cancel ,then erase all data
        self.Clear(True)
            
    # if user press help button
    def Help(self):
        """
        This function open the help window on click of help button.
        """
        
        # creating help as Main window
        self.help = QtWidgets.QMainWindow()
        # creating help ui from its class
        self.help_ui = Ui_HelpWindow()
        # setting help ui in help window
        self.help_ui.setupUi(self.help)
        # show the help window
        self.help.show()
        
        # if user press close in help window
        def Close():
            # help window will be closed
            self.help.close()
        # when close button is pressed in help ui 
        self.help_ui.btnClose.clicked.connect(Close)
    
    # this function retranslate the GUI of Main Window
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Email Sender"))
        self.EmailTo.setStatusTip(_translate("MainWindow", "Enter Receiver Email Here!"))
        self.EmailSubject.setStatusTip(_translate("MainWindow", "Enter Subject of the Email!"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))
        self.btnSend.setText(_translate("MainWindow", "Send"))
        self.Password.setStatusTip(_translate("MainWindow", "Enter Sender Password Here!"))
        self.Email.setStatusTip(_translate("MainWindow", "Enter Sender Email Here!"))
        self.labelEmail.setText(_translate("MainWindow", "Email:"))
        self.labelPassword.setText(_translate("MainWindow", "Password:"))
        self.labelToList.setText(_translate("MainWindow", "To:"))
        self.labelEmailSubject.setText(_translate("MainWindow", "Subject:"))
        self.labelEmailMessage.setText(_translate("MainWindow", "Message:"))
        self.AppName.setText(_translate("MainWindow", "Email Sender"))
        self.EmailMessage.setPlaceholderText(_translate("MainWindow", "Enter Contet of Message!"))
        self.FromLabel.setText(_translate("MainWindow", "From"))
        self.ToLabel.setText(_translate("MainWindow", "To"))
        self.btnHelp.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
