# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sender.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from email.message import EmailMessage
import smtplib


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(640, 449)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(640, 449))
        
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.EmailTo = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailTo.setGeometry(QtCore.QRect(110, 160, 451, 20))
        
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        
        self.EmailTo.setFont(font)
        self.EmailTo.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.EmailTo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EmailTo.setAutoFillBackground(False)
        self.EmailTo.setStyleSheet("color:black;\n"
"background-color:white;")
        self.EmailTo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.EmailTo.setObjectName("EmailTo")
        
        self.EmailSubject = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailSubject.setGeometry(QtCore.QRect(110, 190, 451, 20))
        
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        
        self.EmailSubject.setFont(font)
        self.EmailSubject.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.EmailSubject.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EmailSubject.setAutoFillBackground(False)
        self.EmailSubject.setStyleSheet("color:black;\n"
"background-color:white;")
        self.EmailSubject.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.EmailSubject.setObjectName("EmailSubject")
        
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(390, 400, 75, 23))
        self.Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Cancel.setAutoFillBackground(False)
        self.Cancel.setStyleSheet("color:black;\n"
"background-color:white;")
        self.Cancel.setAutoDefault(False)
        self.Cancel.setFlat(False)
        self.Cancel.setObjectName("Cancel")
        
        self.Send = QtWidgets.QPushButton(self.centralwidget)
        self.Send.setGeometry(QtCore.QRect(480, 400, 75, 23))
        
        self.Send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Send.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Send.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Send.setAutoFillBackground(False)
        self.Send.setStyleSheet("color:black;\n"
"background-color:white;")
        self.Send.setAutoDefault(False)
        self.Send.setFlat(False)
        self.Send.setObjectName("Send")
        self.Send.clicked.connect(self.Send)
        
        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(370, 100, 191, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Password.setFont(font)
        self.Password.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password.setAutoFillBackground(False)
        self.Password.setStyleSheet("color:black;\n"
"background-color:white;")
        self.Password.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.Email = QtWidgets.QLineEdit(self.centralwidget)
        self.Email.setGeometry(QtCore.QRect(110, 100, 191, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Email.setFont(font)
        self.Email.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Email.setToolTip("")
        self.Email.setWhatsThis("")
        self.Email.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Email.setAutoFillBackground(False)
        self.Email.setStyleSheet("color:black;\n"
"background-color:white;")
        self.Email.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Pakistan))
        self.Email.setText("")
        self.Email.setObjectName("Email")
        self.labelEmail = QtWidgets.QLabel(self.centralwidget)
        self.labelEmail.setGeometry(QtCore.QRect(60, 100, 31, 21))
        self.labelEmail.setObjectName("labelEmail")
        self.labelPassword = QtWidgets.QLabel(self.centralwidget)
        self.labelPassword.setGeometry(QtCore.QRect(310, 100, 51, 21))
        self.labelPassword.setObjectName("labelPassword")
        self.labelToList = QtWidgets.QLabel(self.centralwidget)
        self.labelToList.setGeometry(QtCore.QRect(60, 160, 16, 21))
        self.labelToList.setObjectName("labelToList")
        self.EmailSubject_2 = QtWidgets.QLabel(self.centralwidget)
        self.EmailSubject_2.setGeometry(QtCore.QRect(60, 190, 41, 21))
        self.EmailSubject_2.setObjectName("EmailSubject_2")
        self.EmailMessage = QtWidgets.QLabel(self.centralwidget)
        self.EmailMessage.setGeometry(QtCore.QRect(60, 220, 47, 13))
        self.EmailMessage.setObjectName("EmailMessage")
        self.AppName = QtWidgets.QLabel(self.centralwidget)
        self.AppName.setGeometry(QtCore.QRect(210, 20, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Hv BT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.AppName.setFont(font)
        self.AppName.setObjectName("AppName")
        self.EmailMessage_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.EmailMessage_2.setGeometry(QtCore.QRect(110, 220, 451, 161))
        self.EmailMessage_2.setStatusTip("")
        self.EmailMessage_2.setStyleSheet("color:black;\n"
"background-color:white;")
        self.EmailMessage_2.setObjectName("EmailMessage_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 130, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Help = QtWidgets.QPushButton(self.centralwidget)
        self.Help.setGeometry(QtCore.QRect(580, 20, 41, 23))
        self.Help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Help.setStatusTip("")
        self.Help.setStyleSheet("color:black;\n"
"background-color:white;")
        self.Help.setObjectName("Help")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Tab Order
        MainWindow.setTabOrder(self.Email, self.Password)
        MainWindow.setTabOrder(self.Password, self.EmailTo)
        MainWindow.setTabOrder(self.EmailTo, self.EmailSubject)
        MainWindow.setTabOrder(self.EmailSubject, self.EmailMessage_2)
        MainWindow.setTabOrder(self.EmailMessage_2, self.Send)
        MainWindow.setTabOrder(self.Send, self.Cancel)
        
    def Send(self):
        print("Hello world")
        # server = smtplib.SMTP('smtp.gmail.com', 587)
        # server.starttls()
        # # Make sure to give app access in your Google account
        # server.login('Sender_Email', 'Sender_Email_password')
        # email = EmailMessage()
        # email['From'] = 'Sender_Email'
        # email['To'] = receiver
        # email['Subject'] = subject
        # email.set_content(message)
        # server.send_message(email)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Email Sender"))
        self.EmailTo.setStatusTip(_translate("MainWindow", "Enter Receiver Email Here!"))
        self.EmailSubject.setStatusTip(_translate("MainWindow", "Enter Subject of the Email!"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.Send.setText(_translate("MainWindow", "Send"))
        self.Password.setStatusTip(_translate("MainWindow", "Enter Sender Password Here!"))
        self.Email.setStatusTip(_translate("MainWindow", "Enter Sender Email Here!"))
        self.labelEmail.setText(_translate("MainWindow", "Email:"))
        self.labelPassword.setText(_translate("MainWindow", "Password:"))
        self.labelToList.setText(_translate("MainWindow", "To:"))
        self.EmailSubject_2.setText(_translate("MainWindow", "Subject:"))
        self.EmailMessage.setText(_translate("MainWindow", "Message:"))
        self.AppName.setText(_translate("MainWindow", "Email Sender"))
        self.EmailMessage_2.setPlaceholderText(_translate("MainWindow", "Enter Contet of Message!"))
        self.label.setText(_translate("MainWindow", "From"))
        self.label_2.setText(_translate("MainWindow", "To"))
        self.Help.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
